export const partidos = [
    {
        "Numero": "1",
        "Pais1": "México",
        "Pais2": "Sudáfrica",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "11/06/2026",
        "Hora": "21:00",
        "Estadio": "Estadio Azteca",
        "Fase": "Grupo A"
    },
    {
        "Numero": "2",
        "Pais1": "Corea del Sur",
        "Pais2": "República Checa",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "12/06/2026",
        "Hora": "4:00",
        "Estadio": "Estadio Chivas",
        "Fase": "Grupo A"
    },
    {
        "Numero": "3",
        "Pais1": "Canadá",
        "Pais2": "Bosnia y Herzegovina",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "12/06/2026",
        "Hora": "21:00",
        "Estadio": "Estadio Nacional de Canadá",
        "Fase": "Grupo B"
    },
    {
        "Numero": "4",
        "Pais1": "Estados Unidos",
        "Pais2": "Paraguay",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "13/06/2026",
        "Hora": "3:00",
        "Estadio": "SoFi Stadium",
        "Fase": "Grupo D"
    },
    {
        "Numero": "5",
        "Pais1": "Haití",
        "Pais2": "Escocia",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "14/06/2026",
        "Hora": "3:00",
        "Estadio": "MetLife Stadium",
        "Fase": "Grupo C"
    },
    {
        "Numero": "6",
        "Pais1": "Australia",
        "Pais2": "Turquía",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "14/06/2026",
        "Hora": "6:00",
        "Estadio": "Estadio BC Place",
        "Fase": "Grupo D"
    },
    {
        "Numero": "7",
        "Pais1": "Brasil",
        "Pais2": "Marruecos",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "14/06/2026",
        "Hora": "0:00",
        "Estadio": "Gillette Stadium",
        "Fase": "Grupo C"
    },
    {
        "Numero": "8",
        "Pais1": "Catar",
        "Pais2": "Suiza",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "13/06/2026",
        "Hora": "21:00",
        "Estadio": "Levi's Stadium",
        "Fase": "Grupo B"
    },
    {
        "Numero": "9",
        "Pais1": "Costa de Marfil",
        "Pais2": "Ecuador",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "15/06/2026",
        "Hora": "1:00",
        "Estadio": "Lincoln Financial Field",
        "Fase": "Grupo E"
    },
    {
        "Numero": "10",
        "Pais1": "Alemania",
        "Pais2": "Curazao",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "14/06/2026",
        "Hora": "19:00",
        "Estadio": "NRG Stadium",
        "Fase": "Grupo E"
    },
    {
        "Numero": "11",
        "Pais1": "Países Bajos",
        "Pais2": "Japón",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "14/06/2026",
        "Hora": "22:00",
        "Estadio": "AT&T Stadium",
        "Fase": "Grupo F"
    },
    {
        "Numero": "12",
        "Pais1": "Suecia",
        "Pais2": "Túnez",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "15/06/2026",
        "Hora": "4:00",
        "Estadio": "Estadio Monterrey",
        "Fase": "Grupo F"
    },
    {
        "Numero": "13",
        "Pais1": "Arabia Saudita",
        "Pais2": "Uruguay",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "16/06/2026",
        "Hora": "0:00",
        "Estadio": "Hard Rock Stadium",
        "Fase": "Grupo H"
    },
    {
        "Numero": "14",
        "Pais1": "España",
        "Pais2": "Cabo Verde",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "15/06/2026",
        "Hora": "20:00",
        "Estadio": "Mercedes-Benz Stadium",
        "Fase": "Grupo H"
    },
    {
        "Numero": "15",
        "Pais1": "Irán",
        "Pais2": "Nueva Zelanda",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "16/06/2026",
        "Hora": "3:00",
        "Estadio": "Lumen Field",
        "Fase": "Grupo G"
    },
    {
        "Numero": "16",
        "Pais1": "Bélgica",
        "Pais2": "Egipto",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "15/06/2026",
        "Hora": "21:00",
        "Estadio": "SoFi Stadium",
        "Fase": "Grupo G"
    },
    {
        "Numero": "17",
        "Pais1": "Francia",
        "Pais2": "Senegal",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "16/06/2026",
        "Hora": "21:00",
        "Estadio": "MetLife Stadium",
        "Fase": "Grupo I"
    },
    {
        "Numero": "18",
        "Pais1": "Irak",
        "Pais2": "Noruega",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "17/06/2026",
        "Hora": "0:00",
        "Estadio": "Gillette Stadium",
        "Fase": "Grupo I"
    },
    {
        "Numero": "19",
        "Pais1": "Argentina",
        "Pais2": "Argelia",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "17/06/2026",
        "Hora": "3:00",
        "Estadio": "Arrowhead Stadium",
        "Fase": "Grupo J"
    },
    {
        "Numero": "20",
        "Pais1": "Austria",
        "Pais2": "Jordania",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "17/06/2026",
        "Hora": "6:00",
        "Estadio": "Levi's Stadium",
        "Fase": "Grupo J"
    },
    {
        "Numero": "21",
        "Pais1": "Ghana",
        "Pais2": "Panamá",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "18/06/2026",
        "Hora": "2:00",
        "Estadio": "AT&T Stadium",
        "Fase": "Grupo L"
    },
    {
        "Numero": "22",
        "Pais1": "Inglaterra",
        "Pais2": "Croacia",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "17/06/2026",
        "Hora": "21:00",
        "Estadio": "Estadio Nacional de Canadá",
        "Fase": "Grupo L"
    },
    {
        "Numero": "23",
        "Pais1": "Portugal",
        "Pais2": "RD Congo",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "17/06/2026",
        "Hora": "19:00",
        "Estadio": "NRG Stadium",
        "Fase": "Grupo K"
    },
    {
        "Numero": "24",
        "Pais1": "Uzbekistán",
        "Pais2": "Colombia",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "18/06/2026",
        "Hora": "4:00",
        "Estadio": "Estadio Azteca",
        "Fase": "Grupo K"
    },
    {
        "Numero": "25",
        "Pais1": "República Checa",
        "Pais2": "Sudáfrica",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "18/06/2026",
        "Hora": "18:00",
        "Estadio": "Mercedes-Benz Stadium",
        "Fase": "Grupo A"
    },
    {
        "Numero": "26",
        "Pais1": "Suiza",
        "Pais2": "Bosnia y Herzegovina",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "18/06/2026",
        "Hora": "21:00",
        "Estadio": "SoFi Stadium",
        "Fase": "Grupo B"
    },
    {
        "Numero": "27",
        "Pais1": "Canadá",
        "Pais2": "Catar",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "19/06/2026",
        "Hora": "0:00",
        "Estadio": "Estadio BC Place",
        "Fase": "Grupo B"
    },
    {
        "Numero": "28",
        "Pais1": "México",
        "Pais2": "Corea del Sur",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "19/06/2026",
        "Hora": "3:00",
        "Estadio": "Estadio Chivas",
        "Fase": "Grupo A"
    },
    {
        "Numero": "29",
        "Pais1": "Brasil",
        "Pais2": "Haití",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "20/06/2026",
        "Hora": "3:00",
        "Estadio": "Lincoln Financial Field",
        "Fase": "Grupo C"
    },
    {
        "Numero": "30",
        "Pais1": "Escocia",
        "Pais2": "Marruecos",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "20/06/2026",
        "Hora": "0:00",
        "Estadio": "Gillette Stadium",
        "Fase": "Grupo C"
    },
    {
        "Numero": "31",
        "Pais1": "Turquía",
        "Pais2": "Paraguay",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "20/06/2026",
        "Hora": "6:00",
        "Estadio": "Levi's Stadium",
        "Fase": "Grupo D"
    },
    {
        "Numero": "32",
        "Pais1": "Estados Unidos",
        "Pais2": "Australia",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "19/06/2026",
        "Hora": "21:00",
        "Estadio": "Lumen Field",
        "Fase": "Grupo D"
    },
    {
        "Numero": "33",
        "Pais1": "Alemania",
        "Pais2": "Costa de Marfil",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "20/06/2026",
        "Hora": "22:00",
        "Estadio": "Estadio Nacional de Canadá",
        "Fase": "Grupo E"
    },
    {
        "Numero": "34",
        "Pais1": "Ecuador",
        "Pais2": "Curazao",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "21/06/2026",
        "Hora": "2:00",
        "Estadio": "Arrowhead Stadium",
        "Fase": "Grupo E"
    },
    {
        "Numero": "35",
        "Pais1": "Países Bajos",
        "Pais2": "Suecia",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "20/06/2026",
        "Hora": "19:00",
        "Estadio": "NRG Stadium",
        "Fase": "Grupo F"
    },
    {
        "Numero": "36",
        "Pais1": "Túnez",
        "Pais2": "Japón",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "21/06/2026",
        "Hora": "6:00",
        "Estadio": "Estadio Monterrey",
        "Fase": "Grupo F"
    },
    {
        "Numero": "37",
        "Pais1": "Uruguay",
        "Pais2": "Cabo Verde",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "22/06/2026",
        "Hora": "0:00",
        "Estadio": "Mercedes-Benz Stadium",
        "Fase": "Grupo H"
    },
    {
        "Numero": "38",
        "Pais1": "España",
        "Pais2": "Arabia Saudita",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "21/06/2026",
        "Hora": "18:00",
        "Estadio": "Hard Rock Stadium",
        "Fase": "Grupo H"
    },
    {
        "Numero": "39",
        "Pais1": "Bélgica",
        "Pais2": "Irán",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "21/06/2026",
        "Hora": "21:00",
        "Estadio": "SoFi Stadium",
        "Fase": "Grupo G"
    },
    {
        "Numero": "40",
        "Pais1": "Nueva Zelanda",
        "Pais2": "Egipto",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "22/06/2026",
        "Hora": "3:00",
        "Estadio": "Estadio BC Place",
        "Fase": "Grupo G"
    },
    {
        "Numero": "41",
        "Pais1": "Noruega",
        "Pais2": "Senegal",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "23/06/2026",
        "Hora": "2:00",
        "Estadio": "Lincoln Financial Field",
        "Fase": "Grupo I"
    },
    {
        "Numero": "42",
        "Pais1": "Francia",
        "Pais2": "Irak",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "22/06/2026",
        "Hora": "23:00",
        "Estadio": "MetLife Stadium",
        "Fase": "Grupo I"
    },
    {
        "Numero": "43",
        "Pais1": "Argentina",
        "Pais2": "Austria",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "22/06/2026",
        "Hora": "19:00",
        "Estadio": "AT&T Stadium",
        "Fase": "Grupo J"
    },
    {
        "Numero": "44",
        "Pais1": "Jordania",
        "Pais2": "Argelia",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "23/06/2026",
        "Hora": "5:00",
        "Estadio": "Levi's Stadium",
        "Fase": "Grupo J"
    },
    {
        "Numero": "45",
        "Pais1": "Inglaterra",
        "Pais2": "Ghana",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "23/06/2026",
        "Hora": "22:00",
        "Estadio": "Gillette Stadium",
        "Fase": "Grupo L"
    },
    {
        "Numero": "46",
        "Pais1": "Panamá",
        "Pais2": "Croacia",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "24/06/2026",
        "Hora": "1:00",
        "Estadio": "Estadio Nacional de Canadá",
        "Fase": "Grupo L"
    },
    {
        "Numero": "47",
        "Pais1": "Portugal",
        "Pais2": "Uzbekistán",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "23/06/2026",
        "Hora": "19:00",
        "Estadio": "NRG Stadium",
        "Fase": "Grupo K"
    },
    {
        "Numero": "48",
        "Pais1": "Colombia",
        "Pais2": "RD Congo",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "24/06/2026",
        "Hora": "4:00",
        "Estadio": "Estadio Chivas",
        "Fase": "Grupo K"
    },
    {
        "Numero": "49",
        "Pais1": "Escocia",
        "Pais2": "Brasil",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "25/06/2026",
        "Hora": "0:00",
        "Estadio": "Hard Rock Stadium",
        "Fase": "Grupo C"
    },
    {
        "Numero": "50",
        "Pais1": "Marruecos",
        "Pais2": "Haití",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "25/06/2026",
        "Hora": "0:00",
        "Estadio": "Mercedes-Benz Stadium",
        "Fase": "Grupo C"
    },
    {
        "Numero": "51",
        "Pais1": "Suiza",
        "Pais2": "Canadá",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "24/06/2026",
        "Hora": "21:00",
        "Estadio": "Estadio BC Place",
        "Fase": "Grupo B"
    },
    {
        "Numero": "52",
        "Pais1": "Bosnia y Herzegovina",
        "Pais2": "Catar",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "24/06/2026",
        "Hora": "21:00",
        "Estadio": "Lumen Field",
        "Fase": "Grupo B"
    },
    {
        "Numero": "53",
        "Pais1": "República Checa",
        "Pais2": "México",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "25/06/2026",
        "Hora": "5:00",
        "Estadio": "Estadio Azteca",
        "Fase": "Grupo A"
    },
    {
        "Numero": "54",
        "Pais1": "Sudáfrica",
        "Pais2": "Corea del Sur",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "25/06/2026",
        "Hora": "5:00",
        "Estadio": "Estadio Monterrey",
        "Fase": "Grupo A"
    },
    {
        "Numero": "55",
        "Pais1": "Curazao",
        "Pais2": "Costa de Marfil",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "25/06/2026",
        "Hora": "22:00",
        "Estadio": "Lincoln Financial Field",
        "Fase": "Grupo E"
    },
    {
        "Numero": "56",
        "Pais1": "Ecuador",
        "Pais2": "Alemania",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "25/06/2026",
        "Hora": "22:00",
        "Estadio": "MetLife Stadium",
        "Fase": "Grupo E"
    },
    {
        "Numero": "57",
        "Pais1": "Japón",
        "Pais2": "Suecia",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "26/06/2026",
        "Hora": "1:00",
        "Estadio": "AT&T Stadium",
        "Fase": "Grupo F"
    },
    {
        "Numero": "58",
        "Pais1": "Túnez",
        "Pais2": "Países Bajos",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "26/06/2026",
        "Hora": "1:00",
        "Estadio": "Arrowhead Stadium",
        "Fase": "Grupo F"
    },
    {
        "Numero": "59",
        "Pais1": "Turquía",
        "Pais2": "Estados Unidos",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "26/06/2026",
        "Hora": "4:00",
        "Estadio": "SoFi Stadium",
        "Fase": "Grupo D"
    },
    {
        "Numero": "60",
        "Pais1": "Paraguay",
        "Pais2": "Australia",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "26/06/2026",
        "Hora": "4:00",
        "Estadio": "Levi's Stadium",
        "Fase": "Grupo D"
    },
    {
        "Numero": "61",
        "Pais1": "Noruega",
        "Pais2": "Francia",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "26/06/2026",
        "Hora": "21:00",
        "Estadio": "Gillette Stadium",
        "Fase": "Grupo I"
    },
    {
        "Numero": "62",
        "Pais1": "Senegal",
        "Pais2": "Irak",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "26/06/2026",
        "Hora": "21:00",
        "Estadio": "Estadio Nacional de Canadá",
        "Fase": "Grupo I"
    },
    {
        "Numero": "63",
        "Pais1": "Egipto",
        "Pais2": "Irán",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "27/06/2026",
        "Hora": "5:00",
        "Estadio": "Lumen Field",
        "Fase": "Grupo G"
    },
    {
        "Numero": "64",
        "Pais1": "Nueva Zelanda",
        "Pais2": "Bélgica",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "27/06/2026",
        "Hora": "5:00",
        "Estadio": "Estadio BC Place",
        "Fase": "Grupo G"
    },
    {
        "Numero": "65",
        "Pais1": "Cabo Verde",
        "Pais2": "Arabia Saudita",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "27/06/2026",
        "Hora": "2:00",
        "Estadio": "NRG Stadium",
        "Fase": "Grupo H"
    },
    {
        "Numero": "66",
        "Pais1": "Uruguay",
        "Pais2": "España",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "27/06/2026",
        "Hora": "2:00",
        "Estadio": "Estadio Akron",
        "Fase": "Grupo H"
    },
    {
        "Numero": "67",
        "Pais1": "Panamá",
        "Pais2": "Inglaterra",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "27/06/2026",
        "Hora": "23:00",
        "Estadio": "MetLife Stadium",
        "Fase": "Grupo L"
    },
    {
        "Numero": "68",
        "Pais1": "Croacia",
        "Pais2": "Ghana",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "27/06/2026",
        "Hora": "23:00",
        "Estadio": "Lincoln Financial Field",
        "Fase": "Grupo L"
    },
    {
        "Numero": "69",
        "Pais1": "Argelia",
        "Pais2": "Austria",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "28/06/2026",
        "Hora": "4:00",
        "Estadio": "Arrowhead Stadium",
        "Fase": "Grupo J"
    },
    {
        "Numero": "70",
        "Pais1": "Jordania",
        "Pais2": "Argentina",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "28/06/2026",
        "Hora": "4:00",
        "Estadio": "AT&T Stadium",
        "Fase": "Grupo J"
    },
    {
        "Numero": "71",
        "Pais1": "Colombia",
        "Pais2": "Portugal",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "28/06/2026",
        "Hora": "1:30",
        "Estadio": "Hard Rock Stadium",
        "Fase": "Grupo K"
    },
    {
        "Numero": "72",
        "Pais1": "RD Congo",
        "Pais2": "Uzbekistán",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "28/06/2026",
        "Hora": "1:30",
        "Estadio": "Mercedes-Benz Stadium",
        "Fase": "Grupo K"
    },
    {
        "Numero": "73",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "28/06/2026",
        "Hora": "21:00",
        "Estadio": "SoFi Stadium",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "74",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "29/06/2026",
        "Hora": "22:30",
        "Estadio": "Gillette Stadium",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "75",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "30/06/2026",
        "Hora": "3:00",
        "Estadio": "Estadio Monterrey",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "76",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "29/06/2026",
        "Hora": "19:00",
        "Estadio": "NRG Stadium",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "77",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "30/06/2026",
        "Hora": "23:00",
        "Estadio": "MetLife Stadium",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "78",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "30/06/2026",
        "Hora": "19:00",
        "Estadio": "AT&T Stadium",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "79",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "01/07/2026",
        "Hora": "3:00",
        "Estadio": "Estadio Azteca",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "80",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "01/07/2026",
        "Hora": "18:00",
        "Estadio": "Mercedes-Benz Stadium",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "81",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "02/07/2026",
        "Hora": "2:00",
        "Estadio": "Levi's Stadium",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "82",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "01/07/2026",
        "Hora": "22:00",
        "Estadio": "Lumen Field",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "83",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "03/07/2026",
        "Hora": "1:00",
        "Estadio": "Estadio Nacional de Canadá",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "84",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "02/07/2026",
        "Hora": "21:00",
        "Estadio": "SoFi Stadium",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "85",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "03/07/2026",
        "Hora": "5:00",
        "Estadio": "Estadio BC Place",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "86",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "04/07/2026",
        "Hora": "0:00",
        "Estadio": "Hard Rock Stadium",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "87",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "04/07/2026",
        "Hora": "3:30",
        "Estadio": "Arrowhead Stadium",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "88",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "03/07/2026",
        "Hora": "20:00",
        "Estadio": "AT&T Stadium",
        "Fase": "Diesciseisavos de final"
    },
    {
        "Numero": "89",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "04/07/2026",
        "Hora": "23:00",
        "Estadio": "Lincoln Financial Field",
        "Fase": "Octavos de final"
    },
    {
        "Numero": "90",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "04/07/2026",
        "Hora": "19:00",
        "Estadio": "NRG Stadium",
        "Fase": "Octavos de final"
    },
    {
        "Numero": "91",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "05/07/2026",
        "Hora": "22:00",
        "Estadio": "MetLife Stadium",
        "Fase": "Octavos de final"
    },
    {
        "Numero": "92",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "06/07/2026",
        "Hora": "2:00",
        "Estadio": "Estadio Azteca",
        "Fase": "Octavos de final"
    },
    {
        "Numero": "93",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "06/07/2026",
        "Hora": "21:00",
        "Estadio": "AT&T Stadium",
        "Fase": "Octavos de final"
    },
    {
        "Numero": "94",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "07/07/2026",
        "Hora": "2:00",
        "Estadio": "Lumen Field",
        "Fase": "Octavos de final"
    },
    {
        "Numero": "95",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "07/07/2026",
        "Hora": "18:00",
        "Estadio": "Mercedes-Benz Stadium",
        "Fase": "Octavos de final"
    },
    {
        "Numero": "96",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "07/07/2026",
        "Hora": "22:00",
        "Estadio": "Estadio BC Place",
        "Fase": "Octavos de final"
    },
    {
        "Numero": "97",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "09/07/2026",
        "Hora": "22:00",
        "Estadio": "Gillette Stadium",
        "Fase": "Cuartos de final"
    },
    {
        "Numero": "98",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "10/07/2026",
        "Hora": "21:00",
        "Estadio": "SoFi Stadium",
        "Fase": "Cuartos de final"
    },
    {
        "Numero": "99",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "11/07/2026",
        "Hora": "23:00",
        "Estadio": "Hard Rock Stadium",
        "Fase": "Cuartos de final"
    },
    {
        "Numero": "100",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "12/07/2026",
        "Hora": "3:00",
        "Estadio": "Arrowhead Stadium",
        "Fase": "Cuartos de final"
    },
    {
        "Numero": "101",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "14/07/2026",
        "Hora": "21:00",
        "Estadio": "AT&T Stadium",
        "Fase": "Semifinales"
    },
    {
        "Numero": "102",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "15/07/2026",
        "Hora": "21:00",
        "Estadio": "Mercedes-Benz Stadium",
        "Fase": "Semifinales"
    },
    {
        "Numero": "103",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "18/07/2026",
        "Hora": "23:00",
        "Estadio": "Hard Rock Stadium",
        "Fase": "Tercer puesto"
    },
    {
        "Numero": "104",
        "Pais1": "",
        "Pais2": "",
        "g1": "",
        "p1": "",
        "g2": "",
        "p2": "",
        "Fecha": "19/07/2026",
        "Hora": "21:00",
        "Estadio": "MetLife Stadium",
        "Fase": "Final"
    }
]